// Generated by CoffeeScript 1.9.2
(function() {
  var BodyData, WorldData, ok;

  BodyData = (function() {
    function BodyData() {}

    BodyData.prototype.contructor = function() {};

    return BodyData;

  })();

  WorldData = (function() {
    function WorldData(width, height, gravity, sleep) {
      this.width = width;
      this.height = height;
      this.gravity = gravity;
      this.sleep = sleep;
    }

    return WorldData;

  })();

  ok = (function() {
    function ok() {}

    ok.prototype.contructor = function(oi, ola) {
      this.oi = oi;
      this.ola = ola;
    };

    return ok;

  })();

}).call(this);
