// Generated by CoffeeScript 1.9.2
(function() {
  var BodyData, BodyView, Brain, CanvasView, WorldData, giz;

  Brain = (function() {
    function Brain() {}

    Brain.prototype.init = function() {
      this.worldData = new WorldData(10, 50, {
        x: 0,
        y: -10
      }, false);
      this.canvas = new CanvasView();
      return this.canvas.setCanvas();
    };

    return Brain;

  })();

  BodyData = (function() {
    function BodyData() {}

    BodyData.prototype.contructor = function() {};

    return BodyData;

  })();

  WorldData = (function() {
    function WorldData(width1, height1, gravity, sleep) {
      this.width = width1;
      this.height = height1;
      this.gravity = gravity;
      this.sleep = sleep;
    }

    return WorldData;

  })();

  CanvasView = (function() {
    function CanvasView() {}

    CanvasView.prototype.setCanvas = function() {
      var canvas, height, self, width;
      $('canvas').remove();
      $('<canvas></canvas>').prependTo('body');
      canvas = $('canvas');
      width = this.width = $(window).width();
      height = this.height = $(window).height();
      self = this;
      $(window).resize(function() {
        self.setCanvas();
        return 0;
      });
      canvas.attr({
        width: width,
        height: height
      });
      return 0;
    };

    return CanvasView;

  })();

  BodyView = (function() {
    function BodyView() {}

    BodyView.prototype.contructor = function() {};

    return BodyView;

  })();

  giz = new Brain();

  giz.init();

}).call(this);
