// Generated by CoffeeScript 1.9.2
(function() {
  var BodyView, CanvasView;

  CanvasView = (function() {
    function CanvasView() {}

    CanvasView.prototype.contructor = function(width, height) {
      this.width = width;
      this.height = height;
    };

    return CanvasView;

  })();

  BodyView = (function() {
    function BodyView() {}

    BodyView.prototype.contructor = function() {};

    return BodyView;

  })();

}).call(this);
